name: build-and-deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # job.id
  cache-and-install:
    runs-on: ubuntu-latest

    env:
      NODE_VERSION: "16"

    # more information https://github.com/marketplace?type=actions
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build site
        run: pnpm build

      - name: Vercel Deploy
        uses: amondnet/vercel-action@v20
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }} # Optional
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID}}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID}}
          working-directory: blog/.vuepress/dist
          vercel-args: "--prod" # Optional
